#!/usr/bin/env bash
# =============================================================================
# modules/stack/caddyfile.sh — Caddyfile generator
#
# Generates Caddyfile with HTTPS, security headers, gzip+zstd, PHP-FPM
# reverse proxy, JSON access log, and health endpoint on port 80.
# Same determinism + idempotency contract as compose.sh.
# =============================================================================

set -euo pipefail

wpgovern::stack::caddyfile::generate() {
    local domain="${WPGOVERN_DOMAIN:?WPGOVERN_DOMAIN is required}"
    local le_email="${WPGOVERN_LE_EMAIL:-${WPGOVERN_OPERATOR_EMAIL:-}}"
    local install_dir="${WPGOVERN_INSTALL_DIR:?WPGOVERN_INSTALL_DIR is required}"

    if [[ -z "$le_email" ]]; then
        wpgovern::bootstrap::log "ERROR: WPGOVERN_LE_EMAIL or WPGOVERN_OPERATOR_EMAIL required"
        wpgovern::state::mark_phase_failed "stack" "caddyfile: LE email not set"
        return 1
    fi

    local output_file="${install_dir}/Caddyfile"
    local tmp_file
    tmp_file="$(mktemp "${output_file}.tmp.XXXXXX")"
    _wpgovern_stack_caddyfile_write "$tmp_file" "$domain" "$le_email" \
        || { rm -f "$tmp_file"; return 1; }

    local new_hash
    new_hash="$(sha256sum "$tmp_file" | cut -d' ' -f1)" || { rm -f "$tmp_file"; return 1; }

    if [[ -f "$output_file" ]]; then
        local existing_hash
        existing_hash="$(sha256sum "$output_file" | cut -d' ' -f1)"
        if [[ "$existing_hash" == "$new_hash" ]]; then
            wpgovern::bootstrap::log "Caddyfile unchanged — skipping"
            wpgovern::state::set_fact "stack.caddyfile.config_sha256" "$new_hash"
            return 0
        fi
    fi

    mv "$tmp_file" "$output_file"
    wpgovern::state::set_fact "stack.caddyfile.config_path" "$output_file"
    wpgovern::state::set_fact "stack.caddyfile.config_sha256" "$new_hash"
    wpgovern::bootstrap::log "Generated Caddyfile (sha256:${new_hash})"
}

_wpgovern_stack_caddyfile_write() {
    local out="$1"
    local domain="$2"
    local le_email="$3"

    cat > "$out" <<CADDYFILE
# Caddyfile — generated by wpgovern H.2 stack module
# Do not edit by hand. Governance-tracked file.
# Re-run wpgovern-install.sh to regenerate.

{
    email ${le_email}
}

${domain} {
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
        Permissions-Policy "geolocation=(), microphone=(), camera=()"
        -Server
    }

    encode gzip zstd

    php_fastcgi php:9000

    file_server

    log {
        output file /data/access.log
        format json
    }
}

:80 {
    respond /health "ok" 200
}
CADDYFILE
}
