#!/usr/bin/env bash
# =============================================================================
# modules/stack/compose.sh — Docker Compose stack generator
#
# Generates docker-compose.yml with digest-pinned images, explicit bind-mounts,
# restart policies, and healthchecks on all four services.
#
# Determinism contract: same inputs → byte-identical output every time.
# Idempotency: if existing file matches generated hash, no-op (file untouched).
# No :latest tags. No anonymous volumes for governed paths.
# =============================================================================

set -euo pipefail

wpgovern::stack::compose::generate() {
    local domain="${WPGOVERN_DOMAIN:?WPGOVERN_DOMAIN is required}"
    local install_dir="${WPGOVERN_INSTALL_DIR:?WPGOVERN_INSTALL_DIR is required}"
    local db_root_pw="${WPGOVERN_DB_ROOT_PASSWORD:?WPGOVERN_DB_ROOT_PASSWORD is required}"
    local db_wp_pw="${WPGOVERN_DB_WP_PASSWORD:?WPGOVERN_DB_WP_PASSWORD is required}"

    # Read pinned digests from state
    local caddy_digest mariadb_digest php_digest
    caddy_digest="$(wpgovern::state::get_fact "stack.images.caddy_digest")"
    mariadb_digest="$(wpgovern::state::get_fact "stack.images.mariadb_digest")"
    php_digest="$(wpgovern::state::get_fact "stack.images.php_digest")"

    if [[ -z "$caddy_digest" || -z "$mariadb_digest" || -z "$php_digest" ]]; then
        wpgovern::bootstrap::log "ERROR: image digests missing from state — run images.pin first"
        wpgovern::state::mark_phase_failed "stack" "compose: image digests not in state"
        return 1
    fi

    local output_file="${install_dir}/docker-compose.yml"
    local tmp_file
    tmp_file="$(mktemp "${output_file}.tmp.XXXXXX")"
    _wpgovern_stack_compose_write \
        "$tmp_file" "$install_dir" \
        "$caddy_digest" "$mariadb_digest" "$php_digest" \
        "$db_root_pw" "$db_wp_pw" || { rm -f "$tmp_file"; return 1; }

    local new_hash
    new_hash="$(sha256sum "$tmp_file" | cut -d' ' -f1)" || { rm -f "$tmp_file"; return 1; }

    # Idempotency: no-op if existing file is byte-identical
    if [[ -f "$output_file" ]]; then
        local existing_hash
        existing_hash="$(sha256sum "$output_file" | cut -d' ' -f1)"
        if [[ "$existing_hash" == "$new_hash" ]]; then
            wpgovern::bootstrap::log "docker-compose.yml unchanged — skipping"
            wpgovern::state::set_fact "stack.compose.config_sha256" "$new_hash"
            return 0
        fi
    fi

    # Atomic install
    mv "$tmp_file" "$output_file"
    wpgovern::state::set_fact "stack.compose.config_path" "$output_file"
    wpgovern::state::set_fact "stack.compose.config_sha256" "$new_hash"
    wpgovern::bootstrap::log "Generated docker-compose.yml (sha256:${new_hash})"
}

_wpgovern_stack_compose_write() {
    local out="$1"
    local install_dir="$2"
    local caddy_digest="$3"
    local mariadb_digest="$4"
    local php_digest="$5"
    local db_root_pw="$6"
    local db_wp_pw="$7"

    cat > "$out" <<COMPOSE
# docker-compose.yml — generated by wpgovern H.2 stack module
# Do not edit by hand. Governance-tracked file.
# Re-run wpgovern-install.sh to regenerate.

services:

  caddy:
    image: caddy:2@${caddy_digest}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${install_dir}/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${install_dir}/caddy/data:/data
      - ${install_dir}/caddy/config:/config
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  mariadb:
    image: mariadb:10.11@${mariadb_digest}
    restart: unless-stopped
    volumes:
      - ${install_dir}/mariadb/data:/var/lib/mysql
      - ${install_dir}/my.cnf:/etc/mysql/conf.d/wpgovern.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: "${db_root_pw}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: "${db_wp_pw}"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  php:
    image: wordpress:6.5-php8.2-fpm@${php_digest}
    restart: unless-stopped
    volumes:
      - ${install_dir}/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: "${db_wp_pw}"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'php-fpm: master' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
COMPOSE
}
