#!/usr/bin/env bash
# =============================================================================
# modules/stack/mycnf.sh — my.cnf generator
#
# Generates MariaDB configuration tuned for CX22 (4GB RAM):
#   - utf8mb4 charset/collation
#   - InnoDB 2GB buffer pool
#   - Binary logging for H.6 PITR
#   - TLS required
#   - max_connections = 50
# Same determinism + idempotency contract as compose.sh.
# =============================================================================

set -euo pipefail

wpgovern::stack::mycnf::generate() {
    local install_dir="${WPGOVERN_INSTALL_DIR:?WPGOVERN_INSTALL_DIR is required}"

    local output_file="${install_dir}/my.cnf"
    local tmp_file
    tmp_file="$(mktemp "${output_file}.tmp.XXXXXX")"
    _wpgovern_stack_mycnf_write "$tmp_file" || { rm -f "$tmp_file"; return 1; }

    local new_hash
    new_hash="$(sha256sum "$tmp_file" | cut -d' ' -f1)" || { rm -f "$tmp_file"; return 1; }

    # H.2.1-9: detect operator modification before deciding to overwrite
    if [[ -f "$output_file" ]]; then
        local existing_hash
        existing_hash="$(sha256sum "$output_file" | cut -d' ' -f1)"
        local previous_hash
        previous_hash="$(wpgovern::state::get_fact "stack.mycnf.config_sha256")"

        if [[ -n "$previous_hash" && "$existing_hash" != "$previous_hash" ]]; then
            wpgovern::bootstrap::log "WARNING: my.cnf has been modified outside the installer"
            wpgovern::bootstrap::log "  expected hash: $previous_hash"
            wpgovern::bootstrap::log "  actual hash:   $existing_hash"
            wpgovern::bootstrap::log "  Overwriting with regenerated content."
        fi

        # H.2.1-4 + idempotency: no-op when generated content matches existing
        if [[ "$existing_hash" == "$new_hash" ]]; then
            rm -f "$tmp_file"
            wpgovern::bootstrap::log "my.cnf unchanged — skipping"
            wpgovern::state::set_fact "stack.mycnf.config_sha256" "$new_hash"
            return 0
        fi
    fi

    mv "$tmp_file" "$output_file"
    wpgovern::state::set_fact "stack.mycnf.config_path" "$output_file"
    wpgovern::state::set_fact "stack.mycnf.config_sha256" "$new_hash"
    wpgovern::bootstrap::log "Generated my.cnf (sha256:${new_hash})"
}

_wpgovern_stack_mycnf_write() {
    local out="$1"

    cat > "$out" <<MYCNF
# my.cnf — generated by wpgovern H.2 stack module
# Do not edit by hand. Governance-tracked file.
# Re-run wpgovern-install.sh to regenerate.

[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# InnoDB tuning for CX22 (4GB RAM)
innodb_buffer_pool_size = 2G
innodb_log_file_size = 256M
innodb_flush_method = O_DIRECT
innodb_file_per_table = 1

# Binary logging (required for H.6 PITR)
log-bin = /var/lib/mysql/binlog
binlog_format = ROW
expire_logs_days = 14
server-id = 1

# TLS — require encrypted transport for all connections
require_secure_transport = ON

# Connection limits
max_connections = 50
max_allowed_packet = 64M

# Slow query log
slow_query_log = 1
slow_query_log_file = /var/lib/mysql/slow.log
long_query_time = 2
MYCNF
}
