#!/usr/bin/env bats
# =============================================================================
# test_h5_real_integration.bats — THE most important tests in H.5.
#
# Runs against the ACTUAL Python control plane (v52.1) via h5_integration_runner.py.
# Exercises the real composition; not mocks. If these tests pass, H.5 delivers its value.
#
# Uses isolated root_dir (not /opt/wpgovern) via the runner's WPGovernConfig override.
# =============================================================================

RUNNER="${BATS_TEST_DIRNAME}/h5_integration_runner.py"
REPO_DIR="$(cd "${BATS_TEST_DIRNAME}/.." && pwd)"
SDIST="${REPO_DIR}/installer/vendor/wpgovern-0.1.0.tar.gz"

setup() {
    TEST_TMPDIR="$(mktemp -d)"
    ISOLATED_ROOT="${TEST_TMPDIR}/governance_root"
    INSTALL_DIR="${TEST_TMPDIR}/install_dir"
    mkdir -p "$ISOLATED_ROOT" "$INSTALL_DIR"

    # Create the four governed config files (minimal content for hash computation)
    for f in docker-compose.yml Caddyfile my.cnf wp-config.php; do
        printf '# wpgovern governed file: %s\n# generated by H.5 integration test\n' "$f" \
            > "${INSTALL_DIR}/${f}"
    done

    PYTHON_BIN="${REPO_DIR}/.venv/bin/python3"
    if [[ ! -x "$PYTHON_BIN" ]]; then
        PYTHON_BIN="python3"
    fi
}

teardown() {
    rm -rf "$TEST_TMPDIR"
}

_require_sdist() {
    [[ -f "$SDIST" ]] || skip "vendored sdist not present — skipping real integration test"
    command -v python3 >/dev/null 2>&1 || skip "python3 not available"
}

_install_to_venv() {
    local venv_dir="${TEST_TMPDIR}/venv"
    python3 -m venv "$venv_dir" >/dev/null 2>&1
    # Note: --no-index is correct for production; the integration test uses network for deps
    "${venv_dir}/bin/pip" install --quiet "$SDIST" >/dev/null 2>&1
    PYTHON_BIN="${venv_dir}/bin/python3"
}

@test "H.5 integration: byte-one ceremony against real Python control plane" {
    _require_sdist
    _install_to_venv

    run "$PYTHON_BIN" "$RUNNER" \
        --root-dir "$ISOLATED_ROOT" \
        --install-dir "$INSTALL_DIR" \
        run-ceremony \
        --actor-id "test-installer" \
        --reason "byte-one integration test"

    [[ "$status" -eq 0 ]] || {
        echo "CEREMONY FAILED (exit $status):"
        echo "$output"
        return 1
    }

    # Signed baseline must exist on disk
    local baseline_count
    baseline_count="$(find "${ISOLATED_ROOT}" -name "*.json" -path "*/baselines/*" 2>/dev/null | wc -l)"
    [[ "$baseline_count" -ge 1 ]] || {
        echo "No baseline JSON found in ${ISOLATED_ROOT}"
        return 1
    }

    # Active pointer must exist
    local active_pointer="${ISOLATED_ROOT}/state/active.json"
    [[ -f "$active_pointer" ]] || {
        echo "active.json not found at ${active_pointer}"
        return 1
    }

    # governance-check must pass
    run "$PYTHON_BIN" "$RUNNER" \
        --root-dir "$ISOLATED_ROOT" \
        --install-dir "$INSTALL_DIR" \
        governance-check

    [[ "$status" -eq 0 ]] || {
        echo "governance-check failed after successful ceremony (exit $status)"
        return 1
    }
}

@test "H.5 integration: governance-check fails if a governed file is tampered" {
    _require_sdist
    _install_to_venv

    # Run ceremony first
    run "$PYTHON_BIN" "$RUNNER" \
        --root-dir "$ISOLATED_ROOT" \
        --install-dir "$INSTALL_DIR" \
        run-ceremony \
        --actor-id "test-installer" \
        --reason "byte-one integration test"

    [[ "$status" -eq 0 ]] || { echo "Setup ceremony failed: $output"; return 1; }

    # Tamper: append a byte to wp-config.php
    echo "# tampered" >> "${INSTALL_DIR}/wp-config.php"

    # governance-check MUST return non-zero (tamper detected)
    run "$PYTHON_BIN" "$RUNNER" \
        --root-dir "$ISOLATED_ROOT" \
        --install-dir "$INSTALL_DIR" \
        governance-check

    [[ "$status" -ne 0 ]] || {
        echo "TAMPER DETECTION FAILURE: governance-check returned 0 after tampering wp-config.php"
        echo "The governance baseline did NOT detect the file modification."
        echo "H.5 fails to deliver its core value."
        return 1
    }
}
